version: "2"
services:
  db:
    image: postgres
    ports:
      # only needed for access outside compose
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

  creamy-videos:
    build: .
    depends_on:
      - db
    restart: on-failure:10
    environment:
      - CREAMY_VIDEO_DIR=/videos
      - CREAMY_POSTGRES=true
      - CREAMY_POSTGRES_ADDRESS=db:5432
      - CREAMY_APP_URL=
    volumes:
      - videos:/videos
    ports:
     - 3000:3000

volumes:
  db:
  videos: